language: python
matrix:
  include:
  - python: 2.6
  - python: 2.7
    env:
    - secure: "bDqO1+UnF06zC9Gp8XruCCQfw5d+odrrAPHUojvnNI5Vol/WgP3y5qKVBOjvXIh5R6fLQhJ5YP81D10kBw64ygBCTH7Tz8NUt8OhM0NsqAxnebDOBG/mH5l+0jUYwua/pFzQ3SKQG84S0P/c5t3f6RYOV2uMHnkC5PXWw88e8CCfvCxT6eYtVDhfx11isf4bvlEdmea76CM8gejdPLspyBuV7Hx26a6RUF5MIuCj42Wl2j5aeVoTFKrQ+Uv7kz+Z2LnhhU6a2gebQZWceRaGTCed12sglgxuESk2RohYs9HRexaY5fQRKDufcg1NvSQczMTO24BMiw+TZwR4rklNz4StkU4iPbXS9kGLlCehmxCH7ZwaD0Od/pc7nq3bA/g7yB9BoclEaNBG0TElv+yQkFOad/2U6GZygZvbNqbToZhLOIMIDOy9dkLaqqVR6IbSDfwnuDLwNXKn2Zt+4qayarUkcX472JsC+OaHNYQhIb03n4OwsAt02Zzn+/at2zmvxqtEgr8cprq304Ej67mNCLJl+cgwdyGPVO9VXOohaT3xjjr1Qs5TFn7znNpQbt2eVRYbtmUC35/AzDs1T8TPdHaW2IB/1dgUAernBliqtUyA4YRXbl6FjmTwBBR6A5WDpX6jj+c0tRa8VJ6KC71GQaGIjGhR4HshC6J1+Lo9tlk="
    - secure: "jU/iArlVWRC5nZ1A+I3/GZY2XVCdGkEIE56OMVtQl+5mvYiivYDsS5UjVUWctnUEdb6pyNY8AL60clMjQ/+ofETXh1rJKvFmOEM1zIuOMmIP0aX6gnZs1aw+zxFNul3StxHZsY6JETwRmjdXlhedY6Z6vNedXc2OmbHNoCjtlyDBL7MZirE8A97N/MDrQVxiLM5t36QDo74XffY39Lc+RfUYqcCyC21B9qpiXiyyGjYtTaprHAtagtrMDAFrOXf1CTBGlrzZmIGUPhBq4U47Yzb+tEh9D9umTD94a+2n5DjhT3cm4rZNtRfj6KTsavmWYOFB/wSDKbYHh6T0nqxcOISFyWaVS70V/NAyi7vyUojmEDN8UIuOmqvhmlKuxa+pf7bsRNt3FLqMY5T8MWtfdYqNtv7d37tF7qzC/Z/tVOvBazgtzyDxo88TusV1JTMXx9ctBaXEWaqSPg160s6lSYMBXQB95OcQNtYM2INJaZmYBmy0G96lvWN8b7WAFH1menXPNgQ0kjpj8dpKKgPHLnKWVtDbX2THM/yV9pgEifdJ1NhBOKXeIHFwP/AUkxwTjuJ6taQYjQqmKKtxeDa0HlGr4DmyoL/opr0dlI9nBcrmm9GktP7E25AAwU6+CZ3T+be0UCbaIl41x+pfa3L+C6zhuJHcbzEb+N8GOgmQHow="
    - BOB_DOCUMENTATION_SERVER=https://www.idiap.ch/software/bob/docs/latest/bioidiap/%s/master
    - BOB_UPLOAD_WHEEL="--universal"
  - python: 3.3
  - python: 3.4
before_install:
- sudo add-apt-repository -y ppa:biometrics/bob
- sudo apt-get update -qq
- sudo apt-get install -qq --force-yes libboost-all-dev libblitz1-dev libhdf5-serial-dev libatlas-dev libatlas-base-dev liblapack-dev texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended
- pip install --find-links https://www.idiap.ch/software/bob/wheels/travis/ --use-wheel sphinx nose numpy coverage
- pip install --find-links https://www.idiap.ch/software/bob/wheels/travis/ --use-wheel --pre -r requirements.txt coveralls
install:
- python bootstrap-buildout.py
- ./bin/buildout buildout:develop=. buildout:extensions=bob.buildout buildout:auto-checkout=
script:
- ./bin/bob_dbmanage.py casme2 download
- ./bin/coverage run --source=bob.db.casme2 ./bin/nosetests -sv
- ./bin/sphinx-build -b doctest docs sphinx
- ./bin/sphinx-build -b html docs sphinx
after_success:
- coveralls
- wget https://raw.githubusercontent.com/bioidiap/bob.extension/master/scripts/upload-{sphinx,wheel}.sh
- chmod a+x upload-sphinx.sh upload-wheel.sh
- ./upload-sphinx.sh
- ./upload-wheel.sh
